#!/usr/bin/python

import os

home=os.environ['HOME']
path=os.environ['PATH']

pathlst = path.split(":")


def process_path(p):
    if p.startswith(home):
        p = "~/" + p [len(home) + 1: ]
    return p


def get_pathlist( ):
    lst = []
    inlist = set()
    for p in pathlst:
        if p and not (p in inlist):
            inlist.add(p)
            lst += [ p ]
    return lst


def print_pathlist( ):
    for p in get_pathlist( ):
        print process_path(p)

if __name__ == "__main__":
    print_pathlist( )


